services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: crt-backend-dev
    ports:
      - "7070:7070"
    volumes:
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
      - maven_cache:/root/.m2
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: crt-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  maven_cache:
